# .github/workflows/build.yml
on:
  push:
    branches: [master]

name: CI
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: docker
        run: |
          docker build -t base9-builder:latest .
          docker run -name current -i base9-builder:latest
      - name: copy
        run: |
          docker cp current:/app/target/release/base9-builder ./
          docker cp -r current:/app/pkg ./
      - name: manula_test
        run: |
          ls .
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/base9-builder
